export const enpoints = {
    login: 'auth/login',
    register: 'auth/register',
    validateToken: 'auth/validateToken',
    validateAdmin: 'auth/validateAdmin',
    users: 'users',
    banUser: 'users/ban',
    unbanUser: 'users/unban',
    allPosts: 'posts',
    postById: 'posts/id',
    createPost: 'posts/create',
    recentPosts: 'posts/recent',
    popularPosts: 'posts/popular',
    updatePost: 'posts/update',
    deletePost: 'posts/delete',
    likePost: 'posts/like',
    postOwnership: 'posts/validateOwnership',
    categories: 'categories',
};